epl_pipeline:
  target: local

  outputs:
    local:
      type: duckdb
      path: "{{ env_var('EPL_DB_PATH', '../data/epl_pipeline.duckdb') }}"
      threads: 4

    cloud:
      type: athena
      s3_staging_dir: "{{ env_var('ATHENA_S3_STAGING_DIR', 's3://epl-pipeline-athena-results-dev/dbt-staging/') }}"
      s3_data_dir: "{{ env_var('ATHENA_S3_DATA_DIR', 's3://epl-pipeline-data-lake-dev/dbt/') }}"
      region_name: "{{ env_var('AWS_REGION', 'us-east-2') }}"
      database: "{{ env_var('GLUE_DATABASE', 'epl_pipeline_dev') }}"
      schema: mart
      work_group: "{{ env_var('ATHENA_WORKGROUP', 'epl-pipeline-dev') }}"
      threads: 4
      num_retries: 3

    redshift:
      type: redshift
      host: "{{ env_var('REDSHIFT_HOST') }}"
      port: 5439
      dbname: dev
      schema: mart
      user: "{{ env_var('REDSHIFT_USER', 'admin') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      threads: 4
      connect_timeout: 30
