import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import Navigation from "@/components/Navigation";

export const metadata: Metadata = {
  title: "EPL Analytics | 2025-26 Premier League",
  description: "Premier League 2025-26 season analytics dashboard — live pipeline",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[#0a0a0f] text-gray-200 antialiased">
        {/* Subtle soccer pitch background texture */}
        <div className="pitch-bg" aria-hidden="true" />

        <Navigation />

        {/* Simulated data disclaimer */}
        <div className="bg-amber-500/[0.08] border-b border-amber-500/20">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 py-2 flex items-center gap-2 text-[11px] text-amber-400/90">
            <span>⚠️</span>
            <p>
              <span className="font-semibold">Simulated 2025/26 season data</span> — This dashboard demonstrates a production-grade data pipeline architecture. Player rosters and match results are generated by football-data.org for the upcoming season and may not reflect real transfers or lineups.
            </p>
          </div>
        </div>

        <main className="max-w-7xl mx-auto px-4 sm:px-6 py-6 sm:py-8 animate-fade-in">
          {children}
        </main>

        <Analytics />

        <footer className="border-t border-white/[0.04] mt-16">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
            <div className="flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-gray-500">
              <p className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-[#00ff85] inline-block" />
                EPL Analytics Dashboard · 2025-26 Season
              </p>
              <p>AWS Cloud · Lambda · S3 · Step Functions · ECS Fargate · Athena · CloudFront · Terraform IaC</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
